#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case $1 in
  start)
    stat_busy "Starting PiTalk"
    su - picam -c "nohup /home/picam/bin/start_stream 2>&1 > /dev/null &"
    stat_done
    ;;
  stop)
    stat_busy "Stopping PiTalk"
    ps u -u picam | grep -i vlc | awk '{print $2}' | xargs kill
    stat_done
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"

esac
exit 0
